name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - pnpm-lock.yaml
      - packages/**
      - packages/app-common/**
      - api/**
      - client/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm

      - name: Run CI
        run: pnpm run ci --concurrency=100%
